### ISSUE TITLE
Switch to yarn instead of npm

### ISSUE THREAD

**Issue by okonet** [MoOx/npmpub#13]
If the project has `yarn.lock` I think it's safe to switch to `yarn install` instead of `npm install`

**Comment by MoOx** [comment]
Definitely! Would be awesome to have this indeed.
Btw, does yarn publish just wrap npm publish?

**Comment by okonet** [comment]
I think so

**Comment by MoOx** [comment]
One problem I ran into is that yarn does not install all .bin files in node_modules/.bin, it only takes the one listed in YOUR package.json, so github-release-from-changelog bin is missing (like for npm2).

**Comment by FDiskas** [comment]
@MoOx Its fixed in newest yarn version

**Comment by MoOx** [comment]
Nice!

The interesting thing (by keeping `npm install`) is that you can get error you won't have been caught in development (because your version are lock). When users install your package, .lock file is not used. So I am not sure if that's a really good idea in practise (cause the goal of this "cleanup install step" is to detect this kind of error right before publishing!

**Comment by FDiskas** [comment]
For me looks like this fresh install is not necessary. NPM and Yarn uses the lock for already

**Comment by MoOx** [comment]
Right. This is kind of a legacy from the pre-lock ages :D
Maybe `--skip-cleanup` should become the default (and we might add `--cleanup`)? Thoughts?

**Comment by MoOx** [comment]
We could also use `yarn --frozen-lockfile`?
